name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Add Nuget source
      run: dotnet nuget add source https://nuget.pkg.github.com/hwndmaster/index.json -n github -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text
    - name: Build
      run: dotnet build -c Release
    - name: Test
      run: dotnet test -c Release --no-build --verbosity normal --logger="trx;logfilename=TestResults.trx"
    - name: Pack Analyzers
      run: dotnet pack Atom.Analyzers/Atom.Analyzers.csproj --configuration Release
    - name: Publish packages to GPR
      run: dotnet nuget push **/*.nupkg --skip-duplicate --api-key ${{ secrets.GITHUB_TOKEN }} --source https://nuget.pkg.github.com/hwndmaster/index.json
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
